{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recyclerview",
    "module": "recyclerview",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7250438"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.2.0.aar",
          "url": "recyclerview-1.2.0.aar",
          "size": 393300,
          "sha512": "37e42a2f86f7b70bcecfdee7228fc6fe680bad834e47b99f6a4fe74ef1114c1f90139eb84dc06c642b620491c80f86c79ee8b3580f8ec8d50dc708071bb71994",
          "sha256": "f68c432db998efac90b9e7f41c1510f097b82220766524d45d04f9b64c6e4d87",
          "sha1": "9d814525b31b29b1b5151b11334b70efbf9d194b",
          "md5": "cc2b703682ddb5ac2023d1d464d6dcec"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.2.0.aar",
          "url": "recyclerview-1.2.0.aar",
          "size": 393300,
          "sha512": "37e42a2f86f7b70bcecfdee7228fc6fe680bad834e47b99f6a4fe74ef1114c1f90139eb84dc06c642b620491c80f86c79ee8b3580f8ec8d50dc708071bb71994",
          "sha256": "f68c432db998efac90b9e7f41c1510f097b82220766524d45d04f9b64c6e4d87",
          "sha1": "9d814525b31b29b1b5151b11334b70efbf9d194b",
          "md5": "cc2b703682ddb5ac2023d1d464d6dcec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recyclerview-1.2.0-sources.jar",
          "url": "recyclerview-1.2.0-sources.jar",
          "size": 321220,
          "sha512": "6650429430f29895099cb68a6125a0587d0d3f64a4514e07403375c3d56bfe956689756b4325709f1214d1a62651a4772bf953b5dce81263d27aaab20151dbac",
          "sha256": "660bc012e25606a5e022b70217386d29d82a17ba9e6fe4d6f88b355f435d38c5",
          "sha1": "3e159bfab49c7e6495fe374e6e5e1e989ee21dcf",
          "md5": "c3406b114d47cfb4199a9423fba2fb0a"
        }
      ]
    }
  ]
}
